- name: allow iri api port remote in firewall
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ haproxy_stats_port }}"
    - "{{ iri_api_port_remote }}"

- name: allow haproxy peering port
  firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ item[0] }}" port port={{ item[1].port }} protocol={{ item[1].proto }} accept'
    permanent: true
    state: enabled
    immediate: true
    zone: public
  with_nested:
    - "{{ groups['fullnode'] | map('extract', hostvars, ['ip']) | list | difference([ip]) }}"
    - {"port": '{{ haproxy_peer_port }}', "proto": "tcp"}
  when: groups['fullnode'] | length > 1
