---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: "Check ansible version >=2.8.0"
      assert:
        msg: "Ansible version 2.8.0 or above is required to run this playbook"
        that:
          - ansible_version.string is version("2.8.0", ">=")
      tags:
        - always
        - check_version
      run_once: yes
      ignore_errors: "{{ ignore_assert_errors }}"

    - name: run gilt overlay
i      command: "gilt --config {{ gilt_config | default('gilt.yml') }} overlay"
      changed_when: false
      run_once: yes
      ignore_errors: "{{ ignore_assert_errors }}"
      tags: always

  vars:
    ansible_connection: local

- hosts: all
  gather_facts: true
  roles:
    - common

- hosts: fullnode
  gather_facts: true
  become: true
  become_method: sudo
  any_errors_fatal: true
  tasks:
    - name: include playbook roles
      tags: always
      include_role:
        name: "{{ roleinputvar }}"
      loop: "{{ fullnode_roles }}"
      loop_control:
        loop_var: roleinputvar
  vars:
    fullnode_roles:
      - docker
      - hornet
      - nginx
      - haproxy
      - monitoring
      - cleanup
