playbook_basename: hornet
hornet_repo_name: gohornet/hornet
hornet_git_url: "https://github.com/{{ hornet_repo_name }}.git"
hornet_releases_url: "https://api.github.com/repos/{{ hornet_repo_name }}/releases"
hornet_releases_download_url: "https://github.com/{{ hornet_repo_name }}/releases/download"
hornet_git_dest: /opt/hornet

# Docker image
hornet_image: gohornet/hornet
# Hornet version
hornet_version: latest

hornet_user: hornet
hornet_group: hornet
hornet_home_path: /var/lib/hornet
hornet_config: "{{ hornet_home_path }}/config.json"
hornet_peers_config: "{{ hornet_home_path }}/peering.json"
hornet_mqtt_config_file: mqtt_config.json
hornet_profiles_config_file: profiles.json
hornet_db_path: "{{ hornet_home_path }}/mainnetdb"
hornet_db_tar: "{{ hornet_home_path }}/snapshot/export.bin"
hornet_db_source: "https://ls.manapotion.io/export.bin"

# How long to wait (seconds) for hornet to
# gracefully stop. This applies for restart/stop.
hornet_timeout_stop: 900

# Ports used by hornet
# For now only peering port is not
# running behind a proxy. Therefore
# all the ports are not allowed to
# connected to, and are either
# served by a proxy or locally only.
hornet_ports:
  peering:
    port: 15600
    proto: tcp
    allow: yes
  autopeering:
    port: 14626
    proto: udp
    allow: yes
  api:
    port: 14265
    proto: tcp
    allow: no
  graph:
    port: 8083
    proto: tcp
    allow: yes
  zmq:
    port: 5556
    proto: tcp
    allow: no
  mqtt:
    port: 1883
    proto: tcp
    allow: no
  dashboard:
    port: 8081
    proto: tcp
    allow: yes
  tanglemonitor:
    port: 4434
    proto: tcp
    allow: yes
  tanglemonitor_api:
    port: 4433
    proto: tcp
    allow: yes

# Set openfiles limit
hornet_nofile_limit: "65535"

# Exclude the commands below from the API.
# Applied only to connections other than localhost/127.0.0.1
# Note: if you are using haproxy, limits are set there.
hornet_remote_limit_api: "removeNeighbors, addNeighbors, getNeighbors"

# Tangle Visualiser/Graph config
tanglevisualiser_git_url: "https://github.com/glumb/IOTAtangle.git"
tanglevisualiser_path: "{{ hornet_home_path }}/tanglevisualiser"

# Tangle Monitor
hornet_monitor_git_url: "https://github.com/unioproject/tanglemonitor.git"
hornet_monitor_path: "{{ hornet_home_path }}/tanglemonitor"
