hornet_git_url: https://github.com/gohornet/hornet.git
hornet_releases_url: https://api.github.com/repos/gohornet/hornet/releases
hornet_git_dest: /opt/hornet
hornet_ports:
  - {port: 15600, proto: tcp}
  - {port: 14625, proto: tcp}

hornet_image: gohonet/hornet
hornet_version: latest
hornet_user: hornet
hornet_group: hornet
hornet_home_path: /var/lib/hornet
hornet_db_path: "{{ hornet_home_path }}/mainnetdb"
hornet_config: "{{ hornet_home_path }}/config.json"
hornet_db_tar: "{{ hornet_home_path }}/latest-export.gz.bin"
hornet_db_source: "https://dbfiles.iota.org/mainnet/hornet/latest-export.gz.bin"

hornet_neighbors:
  - identity: example1.neighbor.com:15600
    preferIPv6: false
  - identity: example2.neighbor.com:15600
    preferIPv6: false

hornet_api_auth_enabled: false
hornet_disable_plugins: []
hornet_enable_plugins: []
hornet_permit_remote_access_list:
 - getNodeInfo
 - getBalances
 - checkConsistency
 - getTransactionsToApprove
 - getInclusionStates
 - getNodeAPIConfiguration
 - wereAddressesSpentFrom
 - broadcastTransactions
 - findTransactions
 - storeTransactions
 - getTrytes

# Unprivileged user to run hornet with
hornet_username: hornet

# Base directory where hornet is installed and runs from
hornet_basedir: /var/lib/hornet

# HORNET configuration dir
hornet_configdir: /etc/hornet

# The TCP port on which HORNET listens for API calls and allows for light wallets to connect to
hornet_api_port: "14265"

# The address to bind on (interface on your node)
# 0.0.0.0 means all interfaces
hornet_tcp_port_bind_address: "0.0.0.0"

# The TCP neighbor peering port
hornet_tcp_port: "15600"

# HORNET ZMQ port
hornet_zmq_port: "5556"

# HORNET ZMQ bind address
hornet_zmq_bind: 127.0.0.1

# HORNET ZMQ enabled (extra metrics from HORNET)
hornet_zmq_enabled: true

# Set openfiles limit
hornet_open_files_limit: 65535

# Exclude the commands below from the API.
# Applied only to connections other than localhost/127.0.0.1
hornet_remote_limit_api: "removeNeighbors, addNeighbors, getNeighbors"

# Let the hornet_api_port bind to all interfaces (0.0.0.0).
# `true` is necessary in order to allow external wallets/APIs to connect without tunneling.
# If set to `false` it will only bind to localhost (127.0.0.1)
api_port_remote: false

# When using distributed LB
# Haproxy stats port with https
haproxy_stats_https: false

# Load balancer max connections (all backends)
lb_max_connections: 720

# Allowed concurrent connections to all hornet backends
# (pow and default)
haproxy_hornet_max_connections: 360

# Allowed concurrent connections to PoW backend
max_connections_pow_backend: 180

# Allowed concurrent connection to default backend (no PoW)
max_connections_backend: 180

# Enable remote auth with password.
# This will only allow connections using basic auth.
haproxy_remote_auth: false
