- import_tasks: image-cadvisor.yml
  tags:
    - cadvisor_docker_image

- name: copy cadvisor sysconfig file
  template:
    src: templates/cadvisor.sysconfig.j2
    dest: "{{ config_dir }}/cadvisor"
    force: "{{ overwrite | default('no') }}"
  notify:
    - restart cadvisor

- name: copy cadvisor systemd service file
  template:
    src: templates/cadvisor.service.j2
    dest: "{{ systemd_dir }}/cadvisor.service"
  notify:
    - restart cadvisor
