- set_fact:
    hornet_arch: >-
      {%- if ansible_architecture in ["armv7l", "armhf", "aarch32"] -%}
      armhf
      {%- elif ansible_architecture in ["armv8l", "aarch64"] -%}
      arm64
      {%- elif ansible_architecture == "x86_64" -%}
      amd64
      {%- endif -%}
  tags: always

- import_tasks: preinstall.yml
  tags:
    - monitoring_preinstall

- import_tasks: firewall.yml
  tags:
    - monitoring_firewall
  when:
    - configure_firewall is defined
    - configure_firewall|bool == True

- import_tasks: alertmanager.yml
  tags:
    - alertmanager_config

- import_tasks: prometheus.yml
  tags:
    - prometheus_config

- import_tasks: node-exporter.yml
  tags:
    - node_exporter_config

- import_tasks: iota-prom-exporter.yml
  tags:
    - iota_prom_exporter_config

- import_tasks: grafana.yml
  tags:
    - grafana_config

- import_tasks: cadvisor.yml
  tags:
    - cadvisor_config

- import_tasks: uninstall.yml
  tags:
    - uninstall
    - uninstall_monitoring
  when:
    - uninstall_playbook is defined
    - uninstall_playbook|bool == True
