{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hornet.serviceAccountName" . }}
  labels:
{{ include "hornet.labels" . | indent 4 }}
{{- end -}}
