# Required, else jq and some other packages fail
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
  when: "ansible_distribution == 'Debian' or ansible_lsb.id == 'Raspbian'"

- name: Install software-properties-common
  apt:
    state: latest
    name: software-properties-common
    update_cache: yes

- name: Install some packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - jq
      - git
      - ufw
      - wget
      - lsof
      - curl
      - screen
      - pv
      - rsync
      - uuid-runtime
      - nano
      - sysstat
      #- atop Disabled due to kernel bug: https://github.com/Atoptool/atop/blob/master/README#L34
      - htop
      - pastebinit
      - openssl
      - bsdmainutils
      - whiptail
      - python3-pip
      - python3-wheel
      - python3-setuptools
      - python3-passlib
      - apache2-utils
  tags:
    - deps
    - scripts
