# Required, else jq and some other packages fail
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
  when: "ansible_distribution == 'Debian' or ansible_lsb.id == 'Raspbian'"

- name: Install software-properties-common
  apt:
    state: latest
    name: software-properties-common
    update_cache: yes

- name: add ansible repository Ubuntu
  apt_repository:
    repo: ppa:ansible/ansible
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version != '20'

- name: add ansible repository Debian
  apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
    state: present
  when: ansible_distribution_major_version != '20'

- name: Install some packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - jq
      - git
      - ufw
      - wget
      - lsof
      - curl
      - screen
      - pv
      - rsync
      - uuid-runtime
      - nano
      - sysstat
      #- atop Disabled due to kernel bug: https://github.com/Atoptool/atop/blob/master/README#L34
      - htop
      - pastebinit
      - openssl
      - bsdmainutils
      - whiptail
      - python3-pip
      - python-passlib
      - apache2-utils
      - ansible
  tags:
    - deps
    - scripts

- name: Install old python-pip
  apt:
    name: "python-pip"
    update_cache: yes
  when: ansible_distribution_major_version != '20'
  tags:
    - deps
    - scripts
