- name: remove hornet image
  when: remove_hornet_image|default(False)|bool
  block:
    - name: "stopping hornet service, this might take a moment..."
      systemd:
        name: hornet.service
        state: stopped
      ignore_errors: yes
    - name: delete hornet image
      docker_image:
        name: "{{ hornet_image }}"
        tag: "{{ hornet_tag }}"
        state: absent
        force_absent: yes

- name: download hornet from dockerhub (for arch amd64 only)
  when:
    - "server_arch == 'amd64'"
    - not build_image|default(False)|bool
  docker_image:
    name: "{{ hornet_image }}:{{ hornet_tag }}"
    source: pull
  register: image_built
  ignore_errors: yes

- name: build hornet image
  when: >
        server_arch != 'amd64' or
        ('failed' in image_built and image_built.failed) or
        build_image|default(False)|bool
  block:

    - name: check hornet image exists
      shell: "/usr/bin/docker images {{ hornet_image }}:{{ hornet_tag }} | grep -q ^hornet"
      changed_when: False
      register: hornet_image_stat
      failed_when: "hornet_image_stat.rc > 1"

    - name: set dockerfile
      set_fact:
        hornet_dockerfile: >-
          {%- if hornet_tag == "v0.3.0" -%}
          Dockerfile
          {%- else -%}
            {%- if server_arch == 'amd64' -%}
            docker/Dockerfile
            {%- else -%}
            docker/Dockerfile.{{ server_arch }}
            {%- endif -%}
          {%- endif -%}

    - name: build hornet image, this can take a moment...
      docker_image:
        build:
          path: "{{ hornet_git_dest }}"
          pull: no
          network: host
          dockerfile: "{{ hornet_dockerfile }}"
          args:
            ARCH: "{% if server_arch == 'amd64' %}x86_64{% else %}{{ server_arch | upper }}{% endif %}"
            TAG: "{{ hornet_tag }}"
        name: "{{ hornet_image }}"
        tag: "{{ hornet_tag }}"
        source: build
      notify:
        - restart hornet
      register: build_image_status
      until: build_image_status is succeeded
      retries: 3
      delay: 2
      when: >
            hornet_image_stat.rc == 1 and
            (images_from_master is not defined or
             images_from_master|bool == False)
