- name: link python3 to python
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    force: yes
    state: link

- name: install python deps via pip
  pip:
    executable: pip3
    name:
     - docker
     - jmespath
  when:
    - ansible_distribution_major_version != '7'

# Backward compatibility for CentOS7
- name: install python deps via pip
  pip:
    executable: /usr/bin/pip
    name:
     - setuptools
     - docker
     - jmespath

- name: "Fix for No module named ssl_match_hostname"
  shell: "test -d /usr/local/lib/python2.7/dist-packages/backports/ssl_match_hostname/ && cp -r /usr/local/lib/python2.7/dist-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports || /bin/true"
  args:
    creates: "/usr/lib/python2.7/dist-packages/backports/ssl_match_hostname/__init__.py"
  when: ansible_distribution == 'Debian'
