- name: allow hornet ports in firewall
  ufw:
    rule: allow
    direction: in
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  with_items: "{{ hornet_ports }}"

- name: allow ssh port firewall
  ufw:
    rule: allow
    direction: in
    proto: tcp
    port: "{{ ssh_port }}"

- name: ufw default outgoing policy allowed
  ufw:
    direction: outgoing
    policy: allow

- name: ensure ufw started and default incoming policy denied
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: Set ufw logging
  ufw:
    logging: "{{ ufw_logging }}"
