- name: "Install Docker Debian/Ubuntu ..."
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Install Docker Centos 7 ..."
  yum:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  when: "ansible_distribution_major_version == '7'"

- name: "Install Docker Centos 8 ..."
  shell: "dnf -y install {{ docker_package }} --nobest"
  when: "ansible_distribution_major_version == '8'"
  register: docker_install_output
  changed_when: "'Nothing to do.' not in docker_install_output.stdout"
  args:
    warn: no

- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

- name: "Fix for No module named ssl_match_hostname"
  shell: "cp -r /usr/local/lib/python2.7/dist-packages/backports/ssl_match_hostname/ /usr/lib/python2.7/dist-packages/backports"
  args:
    creates: "/usr/lib/python2.7/dist-packages/backports/ssl_match_hostname/__init__.py"
  when: ansible_distribution == 'Debian'
