- set_fact:
    hornet_arch: >-
      {%- if ansible_architecture in ["armv7l", "armhf", "aarch32"] -%}
      armhf
      {%- elif ansible_architecture in ["armv8l", "aarch64"] -%}
      arm64
      {%- elif ansible_architecture == "x86_64" -%}
      amd64
      {%- endif -%}
  tags: always

- import_tasks: setup_apt.yml
  tags:
    - common_setup_apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: setup_yum.yml
  tags:
    - common_setup_yum
  when: ansible_distribution == 'CentOS'

- import_tasks: install.yml
  tags:
    - common_install
